### ISSUE TITLE
Wordings

### ISSUE THREAD

**Issue by ondohotola** [ludwig-austermann/typst-din-5008-letter#8]
Save of modifying `wordings.toml`, how do I change the (default) word "Anlagen" to something like "Encl."

**Comment by ludwig-austermann** [comment]
- you could modify the file accordingly, maybe add a category similar to the debug one,
- you could add your own wordings file and include that one, **BUT** apparently it has to be included in the local package directory, or
- you could pass the dictionary (datatype) directly to wordings

Right now only the third option works without changing the package. You could for instance write:
```typst
#import "@local/din-5008-letter:0.1.0"

#let wordings = din-5008-letter.load-wordings("de-formal")
#wordings.insert("attachments", "Encl.")

#show: din-5008-letter.letter.with(wordings: wordings, attachments: ("thing 1", "thing 2"))

#lorem(100)
```

I think that option 2 would be the nicest one, and should at some point be implemented. You can however already take inspiration of the code, which basically just loads a dictionary from some 'languages', and use this directly in your document.

**Comment by ondohotola** [comment]
I chose option one, and since I have no clue how a _Pull Request_ works, here my new `wordings.toml` 

```toml
[de-formal]
salutation = "Sehr geehrte Damen und Herren"
closing = "Mit freundlichen Grüßen"
attachments = "Anlagen"

[de-informal]
salutation = "Hallo"
closing = "Liebe Grüße"
attachments = "Anlagen"

[debug]
salutation = "<salutation>"
closing = "<closing>"
attachments = "<attachments>"

[us]
salutation = "Dear Sir/Madam"
closing = "With Kind Regards"
attachments = "Encl."
```
